apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthmed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthmed-api
  template:
    metadata:
      labels:
        app: healthmed-api
    spec:
      containers:
        - name: healthmed-api
          image: mancinicadu/healthmed-api:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__ConnectionString
              value: "Server=sqlserver;Database=HealthMed;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=True;"

